spring:
  flyway:
    baseline-on-migrate: true
    table: flyway_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    datasource: postgres
    # password: <no password for this demo>